### ISSUE TITLE
定期大会のサムネイルを利用可能な画像に変更する

### ISSUE THREAD

**Issue by MaruMaruyama** [japancartographersassociation/www_develop#101]
変更必要箇所
docs/_posts/
 2023-07-21-topics-conference-21.md
 2023-07-11-topics-conference-20.md

 /assets/img/topics/noimage.jpg
をアセットファイルを入手後、適切な画像に差し替える

**Comment by mapconcierge** [comment]
# 画像サイズ 760 × 520 ピクセル

![image](https://github.com/japancartographersassociation/www_develop/assets/416977/3d09020a-a501-4cd3-97e6-6f4a69ce33d3)

**Comment by mapconcierge** [comment]
# 定期大会用試作データ

![jcacj_annualconference_760x520](https://github.com/japancartographersassociation/www_develop/assets/416977/94b41f12-1d6c-4035-99ad-7f9a85b942a8)

<img width="380" alt="jcacj_annualconference_760x520" src="https://github.com/japancartographersassociation/www_develop/assets/416977/bcfb11ec-f79e-4ce3-8bb8-dd617e82a2f3">


## Keynote ファイル
[jcacj_thumnail_images202307.key.zip](https://github.com/japancartographersassociation/www_develop/files/12117172/jcacj_thumnail_images202307.key.zip)
