### ISSUE TITLE
INFORMATION欄で、機関紙「地図」 の表記が２行になってしまう。

### ISSUE THREAD

**Issue by mapconcierge** [japancartographersassociation/www_develop#168]
`過去さかのぼっていましたが、類似のJournal の投稿がなかったようで、念のための確認です。あとトップページのリンク出ましたが、機関紙「地図」とされた場合文字数オーバーで2行になってしまうようです。`

![image](https://github.com/japancartographersassociation/www_develop/assets/416977/bbefa6d9-d131-437d-817a-9815028a25c6)

**Comment by MaruMaruyama** [comment]
こちらは、前回のやり取りで、文字溢れするため、機関誌のみとすることで合意していたかと思います。
![Screenshot_20231222-093250](https://github.com/japancartographersassociation/www_develop/assets/10541035/aeccec52-ab2d-4e10-9215-9e3edb960ed5)
