### ISSUE TITLE
依頼： サムネイル画像の追加

### ISSUE THREAD

**Issue by mapconcierge** [japancartographersassociation/www_develop#44]
https://dev-lockup.github.io/www_develop_lockupdev/service.html

<img width="1414" alt="スクリーンショット 2022-10-27 11 47 03" src="https://user-images.githubusercontent.com/416977/198179189-5c9bf1b3-4a8d-4083-b26a-c3b0e6975362.png">

「みんなの自然災害伝承碑」と「日本地図学会 GitHubラボ」に
サムネイル画像をそれぞれ１枚追加してもらえますでしょうか。

納品時は、暫定的に Null Island 画像で、あとでこちらで画像を差し替えます。
<img width="400" alt="スクリーンショット 2022-10-27 11 47 03" src="https://dev-lockup.github.io/www_develop_lockupdev/assets/img/topics/noimage.jpg">

**Comment by dev-lockup** [comment]
修正対応いたしました。
https://dev-lockup.github.io/www_develop_lockupdev/service.html

**Comment by mapconcierge** [comment]
# GitHub Lab のサムネイル画像差し替え
* [ ] 以下の画像にサムネイル画像を差し替えお願いいたします！ 解像度は Null Island サイズと同じにしてあります。
<img width="190" alt="githublab4jcacj" src="https://user-images.githubusercontent.com/416977/198928962-1cdaf679-6efd-4638-9d88-af3c3186831e.png">

**Comment by mapconcierge** [comment]
# みんなの自然災害伝承碑 サムネイル画像差し替え
* [ ] 以下の画像にサムネイル画像を差し替えお願いいたします！ 解像度は Null Island サイズと同じにしてあります。

差し替え用画像（380x261）
<img width="190" alt="monumentdenshohi4jcacj_mini" src="https://user-images.githubusercontent.com/416977/198930947-beb34b1a-a673-4a23-b638-35c5347741c5.png">

元画像（高解像度）
<img width="804" alt="monumentdenshohi4jcacj" src="https://user-images.githubusercontent.com/416977/198930951-1a1824f5-28de-4e94-b774-5e921064efd1.png">

**Comment by dev-lockup** [comment]
サムネイル画像対応いたしました。
https://dev-lockup.github.io/www_develop_lockupdev/service.html

**Comment by mapconcierge** [comment]
確認しました！ ありがとうございます！！！
