### ISSUE TITLE
追加： 機関誌「地図」のサムネイル画像追加

### ISSUE THREAD

**Issue by mapconcierge** [japancartographersassociation/www_develop#45]
<img width="1432" alt="スクリーンショット 2022-10-27 12 02 10" src="https://user-images.githubusercontent.com/416977/198181012-bcfafc2a-84eb-4431-bd70-3a850c0251e2.png">

追加： 機関誌「地図」のサムネイル画像追加（サイズはデザイナー判断でOKです。）
https://dev-lockup.github.io/www_develop_lockupdev/service.html

![journal_map](https://user-images.githubusercontent.com/416977/198180850-46c6bb2f-9415-4a91-96d1-e621940293a2.jpg)

**Comment by dev-lockup** [comment]
修正対応いたしました。
https://dev-lockup.github.io/www_develop_lockupdev/service.html

**Comment by mapconcierge** [comment]
確認しました！！！ 閉じます！
