### ISSUE TITLE
置換： 全角（）を半角()に置換

### ISSUE THREAD

**Issue by mapconcierge** [japancartographersassociation/www_develop#46]
置換： このページにある文字列のなかに点在する全角（）をすべて半角()に置換。

https://dev-lockup.github.io/www_develop_lockupdev/activity.html

<img width="1378" alt="スクリーンショット 2022-10-27 12 14 50" src="https://user-images.githubusercontent.com/416977/198182671-35dbf685-2646-41e4-b951-1e8c17d04244.png">

**Comment by dev-lockup** [comment]
修正完了
https://dev-lockup.github.io/www_develop_lockupdev/activity.html

**Comment by mapconcierge** [comment]
確認しました！ 閉じます！
