### ISSUE TITLE
活動紹介の太字修正

### ISSUE THREAD

**Issue by TArahori** [japancartographersassociation/www_develop#47]
研究会等の開催の部分で、③例会の説明と、フォントが太字になっていないので、修正お願い致します。
https://dev-lockup.github.io/www_develop_lockupdev/activity.html

**Comment by mapconcierge** [comment]
ここですね！

<img width="931" alt="スクリーンショット 2022-10-27 13 48 09" src="https://user-images.githubusercontent.com/416977/198194164-4f055e7e-c16d-4d21-ac23-7b571c89393f.png">

**Comment by TArahori** [comment]
はい！その部分になります。よろしくお願いします。

**Comment by dev-lockup** [comment]
修正対応いたしました。
https://dev-lockup.github.io/www_develop_lockupdev/activity.html

**Comment by mapconcierge** [comment]
確認しました！！！
<img width="1048" alt="スクリーンショット 2022-10-28 7 42 03" src="https://user-images.githubusercontent.com/416977/198411518-cee4adab-b7bd-45eb-8cd0-5fc344ee6b74.png">
 
閉じます！
