### ISSUE TITLE
タブレット環境での表示状態確認

### ISSUE THREAD

**Issue by mapconcierge** [japancartographersassociation/www_develop#48]
* [x] タブレット端末でのレイアウト崩れなど起きていないかチェック

**Comment by mapconcierge** [comment]
<img width="631" alt="スクリーンショット 2022-10-27 16 58 41" src="https://user-images.githubusercontent.com/416977/198226037-d8a5d0c6-3732-433f-b9bf-f0cd535aed3b.png">

**Comment by kaitoyoshida** [comment]
@mapconcierge 
簡単に、ですがChromeのエミュレータでiPad pro(1024 x 1366)サイズに対して、
ランドスケープ/ ポートレイトどちらのパターンでも確認し、大きなズレや見切れは無いことを確認しました。

**Comment by mapconcierge** [comment]
ありがとうございます！ 閉じます！！！
