### ISSUE TITLE
スマホ端末での動作チェック

### ISSUE THREAD

**Issue by mapconcierge** [japancartographersassociation/www_develop#49]
* [ ] iOS でレイアウト崩れがないか確認。
* [x] Android でレイアウト崩れがないか確認。

**Comment by mapconcierge** [comment]
<img width="579" alt="スクリーンショット 2022-10-27 17 00 13" src="https://user-images.githubusercontent.com/416977/198226504-17435d57-2a80-4086-9e55-545fedb5424a.png">

**Comment by kaitoyoshida** [comment]
@mapconcierge 
簡単に、ですがChromeのエミュレータでiPhone6/7/8サイズに対して、
ランドスケープ/ ポートレイトどちらのパターンでも確認し、大きなズレや見切れは無いことを確認しました。

**Comment by mapconcierge** [comment]
ありがとうございます！！！ では閉じます！
