### ISSUE TITLE
ファビコンの配置

### ISSUE THREAD

**Issue by kaitoyoshida** [japancartographersassociation/www_develop#51]
@mapconcierge 
現状のHPにファビコン表示が無い？ようでしたので、可能であればJCAアイコンを配置してもよいかな？と思いました。

**Comment by kaitoyoshida** [comment]
JCA logo: http://japancartographersassociation.github.io/www_jcacj_org/img/main/logo.png

**Comment by mapconcierge** [comment]
ローンチ時に favicon チェックします！！！

**Comment by dev-lockup** [comment]
favicon設定いたしました。
https://dev-lockup.github.io/www_develop_lockupdev/

**Comment by mapconcierge** [comment]
確認しました！！！
