### ISSUE TITLE
サービス、表彰実績、組織のtitleテキストがシンプル

### ISSUE THREAD

**Issue by kaitoyoshida** [japancartographersassociation/www_develop#52]
@mapconcierge 
「入会案内」ページなどのhtmlタイトルの内容は「日本地図学会　入会案内」なのに対して、サービス、表彰実績、組織のページについてはそれぞれ「日本地図学会　〇〇」とはいっていないようでしたので起票させていただきます。

**Comment by mapconcierge** [comment]
# 日本地図学会のご案内 → 日本地図学会　活動紹介
* title を "日本地図学会のご案内" → "日本地図学会　活動紹介" に変更 
<img width="321" alt="スクリーンショット 2022-10-27 20 45 36" src="https://user-images.githubusercontent.com/416977/198275872-09172b7d-8c5d-470d-9e1b-b348dc696d46.png">

https://dev-lockup.github.io/www_develop_lockupdev/activity.html

**Comment by mapconcierge** [comment]
# サービス → 日本地図学会　サービス
* [ ] title を "サービス" → "日本地図学会　サービス" に変更 
<img width="390" alt="スクリーンショット 2022-10-27 20 48 18" src="https://user-images.githubusercontent.com/416977/198276490-277ab2e7-4490-4000-89fa-fb2ab98fe7f3.png">

https://dev-lockup.github.io/www_develop_lockupdev/service.html

**Comment by mapconcierge** [comment]
# 表彰実績 → 日本地図学会　表彰実績
* [ ] title を "表彰実績" → "日本地図学会　表彰実績" に変更 

<img width="267" alt="スクリーンショット 2022-10-27 20 49 53" src="https://user-images.githubusercontent.com/416977/198276726-bf82541b-20c6-4f50-af83-deb8214ed47b.png">

https://dev-lockup.github.io/www_develop_lockupdev/award.html

**Comment by mapconcierge** [comment]
# 組織・体制 → 日本地図学会　組織・体制
* [ ] title を "組織・体制" → "日本地図学会　組織・体制" に変更 

<img width="298" alt="スクリーンショット 2022-10-27 20 51 19" src="https://user-images.githubusercontent.com/416977/198277046-f57a7dc6-1dad-42d6-9888-3a14f2d88861.png">

https://dev-lockup.github.io/www_develop_lockupdev/organization.html

**Comment by mapconcierge** [comment]
# 学会賞→ 日本地図学会　学会賞
* [ ] title を "学会賞" → "日本地図学会　学会賞" に変更 

<img width="264" alt="スクリーンショット 2022-10-27 20 54 13" src="https://user-images.githubusercontent.com/416977/198277521-ac07b6cf-ee88-4b8c-ae7f-055f099bbf89.png">


https://dev-lockup.github.io/www_develop_lockupdev/jcacjaward.html

**Comment by mapconcierge** [comment]
# 地図展優秀地図選定→ 日本地図学会　地図展優秀地図選定
* [ ] title を "地図展優秀地図選定" → "日本地図学会　地図展優秀地図選定" に変更 

<img width="284" alt="スクリーンショット 2022-10-27 20 55 16" src="https://user-images.githubusercontent.com/416977/198277719-fade35a9-1a49-4845-a12e-ed19f1f2efb0.png">

https://dev-lockup.github.io/www_develop_lockupdev/mapaward.html

**Comment by mapconcierge** [comment]
# 機関誌 「地図」 最新号目次→ 日本地図学会　機関誌 「地図」 最新号目次
* [ ] title を "機関誌 「地図」 最新号目次" → "日本地図学会　機関誌 「地図」 最新号目次" に変更 

<img width="336" alt="スクリーンショット 2022-10-27 20 57 23" src="https://user-images.githubusercontent.com/416977/198278126-66f2903f-9be3-488a-a3df-9676dcb53f8c.png">

https://dev-lockup.github.io/www_develop_lockupdev/latestjournal.html

**Comment by mapconcierge** [comment]
# Gallary→ 日本地図学会　添付地図目録
* [ ] title を "Gallary" → "日本地図学会　添付地図目録" に変更 
* [ ] ページに表示されているタイトルも "Gallary" → "添付地図目録" に変更

<img width="1185" alt="スクリーンショット 2022-10-27 20 59 17" src="https://user-images.githubusercontent.com/416977/198278601-0849e98a-be53-4591-87d0-9138c5d82059.png">

https://dev-lockup.github.io/www_develop_lockupdev/attachedmaps.html

**Comment by mapconcierge** [comment]
その他、まだ残っていると思います。発見したら報告をよろしくおねがいします！ ＞ 各位

**Comment by dev-lockup** [comment]
各ページ修正対応いたしました。

**Comment by mapconcierge** [comment]
確認しました！！！
