### ISSUE TITLE
Monumen.to 埋め込み作業

### ISSUE THREAD

**Issue by mapconcierge** [japancartographersassociation/www_develop#57]
* [ ] "自然災害伝承碑" タグフィルタの埋め込み
* [ ] "自然災害伝承碑" ランキングの埋め込み
* [ ] Monumen.to 投稿時のライセンス定義
* [ ] Monumen.to 投稿時の Permalink URL 埋め込み機能
* [ ] "自然災害伝承碑" データの定期サルベージ

**Comment by mapconcierge** [comment]
Monumen.to 埋め込み用のURL 

https://monumen.to/matomes/jca

こちらを「みんなの自然災害伝承碑」ページに埋め込みお願いします！
https://dev-lockup.github.io/www_develop_lockupdev/monumento.html

<img width="1461" alt="スクリーンショット 2022-10-31 13 15 16" src="https://user-images.githubusercontent.com/416977/198929697-45a9e57a-31f2-4c13-afa2-c82953f12a4e.png">

**Comment by dev-lockup** [comment]
https://monumen.to/matomes/jca に埋め込み修正完了いたしました。
`<iframe src="https://monumen.to/matomes/jca" frameborder="0"></iframe>`
https://dev-lockup.github.io/www_develop_lockupdev/monumento.html

弊社のテストサーバ上では非表示となっておりますが、本番環境では表示されるかと存じますため、一旦こちらにて納品とさせていただきます。
もし、本番環境で表示崩れ等の不具合がございましたら対応いたしますので、その際はお申し付けくださいませ。

**Comment by mapconcierge** [comment]
確認しました！！ ありがとうございます。

https://dev-lockup.github.io/www_develop_lockupdev/monumento.html

<img width="1512" alt="スクリーンショット 2022-10-31 20 07 33" src="https://user-images.githubusercontent.com/416977/198994933-6995be46-a4cc-44dc-90bc-0cd8a8dd6457.png">
