### ISSUE TITLE
学会賞　ページタイトル下テキスト 作文

### ISSUE THREAD

**Issue by mapconcierge** [japancartographersassociation/www_develop#60]
学会賞　ページタイトル下テキスト
https://jcacj.org/jcacjaward.html

![image](https://user-images.githubusercontent.com/416977/199132221-8f29e346-91d0-484b-89e0-6d9578e47e34.png)

**Comment by mapconcierge** [comment]
# 学会賞

2007年より毎年１回、地図学の理論構築と普及、地図・空間情報などに関する技術の向上に尽力された個人や法人、団体を日本地図学会として表彰しています。論文賞、論文奨励賞、野村正七地図賞、作品・出版賞、教育普及賞、功労賞、特別賞といった多様な評価軸で、受賞理由も含めてすべてこちらにアーカイブしております。

**Comment by dev-lockup** [comment]
ありがとうございます！
テストアップいたしました。
https://dev-lockup.github.io/www_develop_lockupdev/jcacjaward.html

**Comment by mapconcierge** [comment]
確認しました！！ ありがとうございます！

**Comment by mapconcierge** [comment]
PR 反映確認。閉じます！

https://jcacj.org/jcacjaward.html

<img width="1488" alt="スクリーンショット 2022-11-01 11 09 23" src="https://user-images.githubusercontent.com/416977/199143316-c502e0f1-d907-476a-8207-1c2d2f7d0ad1.png">
