### ISSUE TITLE
広報投稿依頼: 定期大会告知

### ISSUE THREAD

**Issue by mapconcierge** [japancartographersassociation/www_develop#84]
[2023-岐阜-定期大会案内-2報最新.pdf](https://github.com/japancartographersassociation/www_develop/files/11619560/2023-.-.-2.pdf)

[2023-岐阜-定期大会案内-2報最新.docx](https://github.com/japancartographersassociation/www_develop/files/11619561/2023-.-.-2.docx)

**Comment by mapconcierge** [comment]
# 日本地図学会　2023年度 定期大会のお知らせ （第２報）

2023年度定期大会を下記の通り開催いたします。会員の皆様には奮ってご参加いただきたく，ご協力をよろしくお願い申し上げます。なお，過去３年間にわたる新型コロナウイルスの蔓延から、全面的にオンラインで実施して来ましたが、今回は従来通りのリアルでの大会として実施する運びとなります。
また、会場も公立図書館としては日本最大規模を誇る、多くの地図類を所蔵する岐阜県図書館との共催で実施できることになりました。地の利を生かした大会にしたいと思います。

日　時：2022年8月26日（土）・27日（日）両日とも10:00~17:00（時間については変更の可能性あり）
　　　　　　　　　　　　　　  ただし、巡検のみ8月25日（金）午後・夜 に開催を準備中です。
会　場：岐阜県図書館
　　　　　　　　　  　　　　　　 〒500-8368 岐阜県岐阜市宇佐４丁目２−１
　　　　　　　　　　　　　　　　　　https://www.library.pref.gifu.lg.jp/
スケジュール（予定）：
・研究発表（口頭発表は26日または27日）
・特別セッション，シンポジウム，ワークショップ, フォーラム等（同上），懇親会（26日夜）
・地図・図書等の展示（都内に展示会場を設け、8月26日11時から27日15時まで、リアルな地図類の展示を予定しています）
・巡検　8月25日　岐阜県内の地図・地図関連箇所の見学・訪問と鵜飼見学（任意）

大会参加費：普通会員等・特別会員団体構成員・学生会員　1000円　非会員　2000円
 岐阜県民は事前登録の上、無料で参加できます。

申し込み：６月５日からPeatixのサイトからのみの申し込みになります。
　　　　https://peatix.com/event/3596020/view?k=9f699f55a64fe1153870e8c99c71ff16dc4abd5e
大会参加
                                                                                   
◎シンポジウム，特別セッションの企画募集
　定期大会のシンポジウム，特別セッションの企画を公募します。提案される代表者の方は，テーマ，趣旨（200字以内），発表者名，発表題目などの提案内容をとりまとめて，電子メールか郵送にて6月30日（金）までに事務局宛お送り下さい。「定期大会発表論文・資料集」のデジタル原稿は 7月16日（日）までに代表者の方が全員分をまとめて提出して下さい。

◎地図・図書展示の出展募集について
　出展希望の方は事務局までお申し出下さい。「定期大会発表論文・資料集(pdf.)」掲載用原稿（デジタル），　　
7月16日（日）を締切りとします。特別会員には詳細をあらためてご案内します。

◎研究発表申し込み要領
　研究発表での発表を希望される方は，下記の要領で学会事務局にお申し込み下さい。

１．申し込み方法
　　研究発表の申し込みと「定期大会発表論文・資料集」の原稿（デジタル）を同時に受け付けます。　締切りは，７月16日（日）（必着）です。発表希望者は，下記の事項についての申し込みメモと「定期大会発表論文・資料集」の原稿を事務局宛てに電子メールの添付ファイルで送信して下さい。

＜申し込み、「定期大会発表論文・資料集原稿」に記入必要な事項＞

1)発表題目　および　キーワード（3～５語）
2)発表者名（所属等）：連名で発表される方はリモート登壇者の名前の後に*印を付けて下さい。リモート登壇者は，普通会員，学生会員，名誉会員または特別会員の団体・企業の構成員、岐阜県民に限ります。各発表の登壇者は，測量CPDの対象になります。
  3)発表題目，発表者名（所属等），およびKeywords（3 ~ 5words）の英文（可能な限り）
　　発表題目・発表者名の英文はそれぞれの和文の下に併記してください。また，キーワードを発表者名の下，本文の上に，二段組みせずに左詰で書き，Keywords（英文）を併記してください。
  　4)なお、発表は現地での口頭発表に限ります。発表メモには発表時のパワーポイント等の資料のデジタル資料の使用の有無を記入してください。

２．「定期大会発表論文・資料集（デジタル原稿）」執筆要領
　1)A4判で上下30mm，左右20mmの余白を設け，本文は二段組で作成して下さい（様式1）。テンプレートとなるファイルを学会のホームページの大会案内頁に掲載していますので，必要に応じてダウンロードしてお使い下さい。電子メールに添付して提出される場合のファイル形式は，Word，一太郎，pdfのいずれかを使用して下さい。A４版の２頁の出力原稿とUSBメモリ等に収めたデジタルファイルを添付してください。

　2)原稿の長さは， A4判見開き2頁です。
　3)提出されたデジタル原稿はそのまま原寸で「pdf定期大会発表論文・資料集」にしますので，出力原稿と同じものでお願いします。なお，地図や図表等を掲載しても結構です。
　4)地図・図書・器材展示目録については，研究発表論文・資料集の掲載に準じますが，ページ数等については事務局にご連絡下さい。
　5)原稿の書式は，学会のホームページに掲載されている，機関誌「地図」の投稿原稿執筆の手引き （http://jcaci.org/file/journal/genkou_tebiki.pdf）の書式に準じて下さい。
３．「定期大会発表論文・資料集」はpdfと当日の現地参加者には印刷冊子で配信・配布を行う予定です。
４．今回は現地でのリアル開催になりますので口頭発表のみとさせていただきます。
（様式1）A4判使用　		

　上下3cm，左右2cmの余白をとってください。タイトルの左側には発表番号が入りますので，余白からさらに2cmあけ，題名と氏名の間，氏名と本文の間も，それぞれ1行あけて下さい。本文は，原則として1頁当たり24字×44行×2段とし，図表は1段または2段で割付けていただきます。タイトルに使用する文字は，ゴシック体（12ポイント），本文で使用する文字は，なるべく明朝体のフォント（10ポイント程度）を使用して下さい。なお，原稿はそのままpdfにしますので、カラー画像を予定しています。
送付先：電子メール　[info@jcacj.org](mailto:info@jcacj.org)
＊メールのタイトルに「2023年度　定期大会予稿集原稿」と代表者氏名を明記してください。

〒153-8522　東京都目黒区青葉台4-9-6　（一財）日本地図センター 内
日本地図学会　事務局　（ホームページ　http://jcacj.org/）
TEL / FAX　03-3485-5410， 

その他・問い合わせ先：
日本地図学会常任委員　企画・集会委員長　太田　弘
　　　　　　　　　　　　　　　　　　　[mapota@keio.jp](mailto:mapota@keio.jp)    携帯：080-33434565
　　　　　　　　　　　　



　
　　　　　　　　　　　　　
　岐阜図書館とホール

**Comment by mapconcierge** [comment]
# 日本地図学会　2023年度 定期大会のお知らせ （第２報）

2023年度定期大会を下記の通り開催いたします。会員の皆様には奮ってご参加いただきたく，ご協力をよろしくお願い申し上げます。

過去３年間にわたる新型コロナウイルスの蔓延から、全面的にオンラインで実施して来ましたが、今回は従来通りのリアルでの大会として実施する運びとなります。

会場も公立図書館としては日本最大規模を誇る、多くの地図類を所蔵する岐阜県図書館との共催で実施できることになりました。地の利を生かした大会にしたいと思います。

## 日時
2022年8月26日（土）・27日（日）両日とも10:00~17:00（時間については変更の可能性あり）
ただし、巡検のみ8月25日（金）午後・夜 に開催を準備中です。

## 会場
岐阜県図書館
〒500-8368 岐阜県岐阜市宇佐４丁目２−１
[岐阜県図書館のウェブサイトへ](https://www.library.pref.gifu.lg.jp/)

## スケジュール（予定）
- 研究発表（口頭発表は26日または27日）
- 特別セッション，シンポジウム，ワークショップ, フォーラム等（同上），懇親会（26日夜）
- 地図・図書等の展示（都内に展示会場を設け、8月26日11時から27日15時まで、リアルな地図類の展示を予定しています）
- 巡検　8月25日　岐阜県内の地図・地図関連箇所の見学・訪問と鵜飼見学（任意）

## 大会参加費
普通会員等・特別会員団体構成員・学生会員　1000円　非会員　2000円
岐阜県民は事前登録の上、無料で参加できます。

## 申し込み
６月５日からPeatixのサイトからのみの申し込みになります。
[Peatix イベントページ

**Comment by TArahori** [comment]
# 日本地図学会　2023年度 定期大会のお知らせ

2023年度定期大会を下記の通り開催いたします。会員の皆様には奮ってご参加いただきたく，ご協力をよろしくお願い申し上げます。

過去３年間にわたる新型コロナウイルスの蔓延から、全面的にオンラインで実施して来ましたが、今回は従来通りのリアルでの大会として実施する運びとなります。

会場も公立図書館としては日本最大規模を誇る、多くの地図類を所蔵する岐阜県図書館との共催で実施できることになりました。地の利を生かした大会にしたいと思います。

## 日時
2023年8月26日（土）・27日（日）両日とも10:00~17:00（時間については変更の可能性あり）
ただし、巡検のみ8月25日（金）午後・夜 に開催を準備中です。

## 会場
岐阜県図書館
〒500-8368 岐阜県岐阜市宇佐４丁目２−１
[岐阜県図書館のウェブサイトへ](https://www.library.pref.gifu.lg.jp/)

## スケジュール（予定）
- 研究発表（口頭発表は26日または27日）
- 特別セッション，シンポジウム，ワークショップ, フォーラム等（同上），懇親会（26日夜）
- 地図・図書等の展示（都内に展示会場を設け、8月26日11時から27日15時まで、リアルな地図類の展示を予定しています）
- 巡検　8月25日　岐阜県内の地図・地図関連箇所の見学・訪問と鵜飼見学（任意）

## 大会参加費
普通会員等・特別会員団体構成員・学生会員　1000円　非会員　2000円
岐阜県民は事前登録の上、無料で参加できます。

## 申し込み
６月５日からPeatixのサイトからのみの申し込みになります。
https://peatix.com/event/3596020/view

### シンポジウム，特別セッションの企画募集

定期大会のシンポジウム，特別セッションの企画を公募します。提案される代表者の方は，テーマ，趣旨（200字以内），発表者名，発表題目などの提案内容をとりまとめて，電子メールか郵送にて7月23日（日）までに事務局宛お送り下さい。「定期大会発表論文・資料集」のデジタル原稿は 7月23日（日）までに代表者の方が全員分をまとめて提出して下さい。

### 地図・図書展示の出展募集について

出展希望の方は事務局までお申し出下さい。「定期大会発表論文・資料集(pdf.)」掲載用原稿（デジタル），7月23日（日）を締切りとします。特別会員には詳細をあらためてご案内します。

### 研究発表申し込み要領

研究発表での発表を希望される方は，下記の要領で学会事務局にお申し込み下さい。

#### １．申し込み方法

研究発表の申し込みと「定期大会発表論文・資料集」の原稿（デジタル）を同時に受け付けます。締切りは，7月23日（日）（必着）です。発表希望者は，下記の事項についての申し込みメモと「定期大会発表論文・資料集」の原稿を事務局宛てに電子メールの添付ファイルで送信して下さい。

※リモートでも発表を検討中です。リモート発表を特に希望の方は担当者までご相談ください。
連絡先：mapota@keio.jp

##### ＜申し込み、「定期大会発表論文・資料集原稿」に記入必要な事項＞
1）発表題目　および　キーワード（3～５語）

2）発表者名（所属等）：連名で発表される方はリモート登壇者の名前の後に\*印を付けて下さい。リモート登壇者は，普通会員，学生会員，名誉会員または特別会員の団体・企業の構成員、岐阜県民に限ります。各発表の登壇者は，測量CPDの対象になります。

3）発表題目，発表者名（所属等），およびKeywords（3~5words）の英文（可能な限り）
発表題目・発表者名の英文はそれぞれの和文の下に併記してください。また，キーワードを発表者名の下，本文の上に，二段組みせずに左詰で書き，Keywords（英文）を併記してください。

4）発表形態（口頭発表，オンライン）

5）発表要旨（200字以内）

##### 注意事項
- 発表要旨は，「定期大会発表論文・資料集」に掲載されます。提出された原稿は原則としてそのまま掲載します。
- 発表時間は，一般口頭発表は15分（討論時間含む）です。ただし，必要に応じて発表時間を変更する場合もあります。
- 発表者は，学会の会員であることが必要です。まだ会員でない方は，申し込みと同時に学会への入会手続きをしてください。

#### ２．発表要旨の提出方法
「定期大会発表論文・資料集」の原稿は，以下の定期大会案内に記載の執筆要領に従い，指定のフォーマット（事務局より提供）を使用してください。また，原稿のファイル形式はPDFとします。

日本地図学会2023年度定期大会のお知らせ
[2023Gifu_entryguide.pdf](https://github.com/japancartographersassociation/www_develop/files/11998711/2023Gifu_entryguide.pdf)
「定期大会発表論文・資料集」の原稿フォーマット
[Templete2023JCA.docx](https://github.com/japancartographersassociation/www_develop/files/11998719/Templete2023JCA.docx)

提出期限は7月23日（日）です。提出物が遅れる場合は，事前に事務局までお知らせください。
原稿は，学会事務局宛に電子メールの添付ファイルで送付してください。

#### ３．学会へのお問い合わせ
ご質問や不明な点がございましたら，以下の連絡先までお気軽にお問い合わせください。
日本地図学会事務局
E-mail: info@jcacj.org
TEL/FAX：03-3485-5410

日本地図学会常任委員　企画・集会委員長　太田　弘
E-mail: mapota@keio.jp
携帯：080-3343-4565
